advanced = {
    'H2OT1': {  'add': 0,
                'canid': 1512,
                'description': 'Coolant Temperature',
                'factor': 0.1,
                'offset': 4,
                'signed': True,
                'size': 2,
                'type': 'int',
                'units': 'F'},
    'MAP1': {   'add': 0,
                'canid': 1512,
                'description': 'Manifold Pressure',
                'factor': 0.1,
                'offset': 0,
                'signed': True,
                'size': 2,
                'type': 'int',
                'units': 'kPa'},
    'THR1': {   'add': 0,
                'canid': 1512,
                'description': 'Throttle Position',
                'factor': 0.1,
                'offset': 6,
                'signed': True,
                'size': 2,
                'type': 'int',
                'units': '%'},
}