advanced = {
"base_id": 1520,
"groups": {
  "0": {
    "seconds": {
      "description": "Seconds ECU has been on",
      "offset": 0,
      "size": 2,
      "signed": False,
      "units": "s",
      "multiply": 1,
      "divide": 1,
      "add": 0,
    },
    "pw1": {
      "description": "Main pulsewidth bank 1",
      "offset": 2,
      "size": 2,
      "signed": False,
      "units": "ms",
      "multiply": 1,
      "divide": 1000,
      "add": 0,
    },
    "pw2": {
      "description": "Main pulsewidth bank 2",
      "offset": 4,
      "size": 2,
      "signed": False,
      "units": "ms",
      "multiply": 1,
      "divide": 1000,
      "add": 0,
    },
    "rpm": {
      "description": "Engine RPM",
      "offset": 6,
      "size": 2,
      "signed": False,
      "units": "RPM",
      "multiply": 1,
      "divide": 1,
      "add": 0,
    },
  },
  "1": {
    "adv_deg": {
      "description": "Final ignition spark advance",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "deg BTDC",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "squirt": {
      "description": "Bitfield of batch fire injector events",
      "offset": 2,
      "size": 1,
      "signed": False,
      "units": "-",
      "multiply": 1,
      "divide": 1,
      "add": 0,
    },
    "engine": {
      "description": "Bitfield of engine status",
      "offset": 3,
      "size": 1,
      "signed": False,
      "units": "-",
      "multiply": 1,
      "divide": 1,
      "add": 0,
    },
    "afrtgt1": {
      "description": "Bank 1 AFR target",
      "offset": 4,
      "size": 1,
      "signed": False,
      "units": "AFR",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "afrtgt2": {
      "description": "Bank 2 AFR target",
      "offset": 5,
      "size": 1,
      "signed": False,
      "units": "AFR",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
  },
  "2": {
    "baro": {
      "description": "Barometric pressure",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "kPa",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "map": {
      "description": "Manifold air pressure",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "kPa",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "mat": {
      "description": "Manifold air temperature",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "deg F",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "clt": {
      "description": "Coolant temperature",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "deg F",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },

  },
  "3": {
    "tps": {
      "description": "Throttle position",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "batt": {
      "description": "Battery voltage",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "V",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "afr1_old": {
      "description": "AFR1 (Deprecated on MS3)",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "AFR",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "afr2_old": {
      "description": "AFR2 (Deprecated on MS3)",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "AFR",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
  },
  "4": {
    "knock": {
      "description": "Indication of knock input",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "egocor1": {
      "description": "EGO bank 1 correction",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "egocor2": {
      "description": "EGO bank 2 correction",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "aircor": {
      "description": "Air density correction",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
  },
  "5": {
    "warmcor": {
      "description": "Warmup correction",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "tpsaccel": {
      "description": "TPS-based acceleration",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "tpsfuelcut": {
      "description": "TPS-based fuel cut",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "barocor": {
      "description": "Barometric fuel correction",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
  },
  "6": {
    "totalcor": {
      "description": "Total fuel correction",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "ve1": {
      "description": "VE value table/bank 1",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "ve2": {
      "description": "VE value table/bank 2",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
# This can be one of two tings, it is duplicated on purpose
    "iacstep": {
      "description": "Stepper idle step number",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "step duty %",
      "multiply": 1,
      "divide": 1,
      "add": 0,
    },
    "iacduty": {
      "description": "or PWM idle value duty",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "step duty %",
      "multiply": 392,
      "divide": 1000,
      "add": 0,
    },

  },
  "7": {
    "cold_adv_deg": {
      "description": "Cold advance",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "deg",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "TPSdot": {
      "description": "Rate of change of TPS",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "%/s",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "MAPdot": {
      "description": "Rate of change of MAP",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "kPa/s",
      "multiply": 1,
      "divide": 1,
      "add": 0,
    },
    "RPMdot": {
      "description": "Rate of change of RPM",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "RPM/s",
      "multiply": 10,
      "divide": 1,
      "add": 0,
    },
  },
  "8": {
    "MAFload": {
      "description": "Synthetic 'load' from MAF",
      "offset": 0,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "fuelload": {
      "description": "'Load' used for fuel table lookup e.g. equals MAP in Speed-Density",
      "offset": 2,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "fuelcor": {
      "description": "Adjustment to fuel from Flex",
      "offset": 4,
      "size": 2,
      "signed": True,
      "units": "%",
      "multiply": 1,
      "divide": 10,
      "add": 0,
    },
    "MAF": {
      "description": "Mass Air Flow (Scaling depend on range, 650g/s shown)",
      "offset": 6,
      "size": 2,
      "signed": True,
      "units": "g/s",
      "multiply": 100,
      "divide": 1,
      "add": 0,
    },
  },

}
}
