name: fixgateway
adopt-info: fixgateway
grade: stable
license: GPL-2.0+
summary: makerplane FIX gateway server
description: |
    A service that collects and distributes avionics data.  FiX is short for "Flight information eXchange" and is a CAN-Aerospace derived protocol specific to experimental aviation needs.

    This snap requires enabling experimental.user-daemons features:
    sudo snap set system experimental.user-daemons=true
    
    Release Notes:
    * Updated to core24 and python 3.12

    Many new plugins that need your help testing, these should be considered beta quality:
    * Flight Data Recoder
    * Replay FDR data from point in time
    * Mavlink plugin for AHRS/GPS data
    * Megasquirt ECU Plugin
    * iFLY plugin, collects waypoints sent by iFLY EFB
    * quorum plugin, negotiate a leader when running multiple gateways
    * improvements to canfix plugin
    * new functions added to compute plugin
    * MGL plugin, import data from an RDAC or export data as an emulated RDAC

    Planned enhancements for future release:
    * Add support for MGL V16 COM radio


issues: https://github.com/makerplane/FIX-Gateway/issues
donation: https://www.paypal.com/donate/?hosted_button_id=VGHHNUG3LRPYL
source-code: https://github.com/makerplane/FIX-Gateway
website: https://makerplane.org/

platforms:
  arm64:
  armhf:
  amd64:

base: core24
confinement: strict

parts:
  extras:
    source: ./extras
    plugin: dump

  fixgateway:
    plugin: python
    source: .
    override-build: |
      craftctl default
      craftctl set version=$(python3 fixgw/version.py)
    stage-packages:
      - libarchive13t64
      - cmake
      - build-essential
      - python3.12-minimal
      - libpython3.12-minimal
      - libpython3.12-stdlib
      - python3-venv
      - python3-minimal
      - python3-pkg-resources
      - python3-numpy
      - python3-lxml
      - python3-psutil
      - libblas3
    build-environment:
      - PARTS_PYTHON_INTERPRETER: python3.12
#      - PIP_VERBOSE: 3
      - PIP_IGNORE_INSTALLED: ''
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages

apps:
  daemon:
    command: bin/fixgw
    daemon: simple
    daemon-scope: user
    # Woud be nice to also support options: https://snapcraft.io/docs/adding-snap-configuration
    restart-condition: always
    plugs: [ home, network-bind, network, can-bus, serial-port, i2c, spi]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas

  server:
    command: bin/fixgw
    plugs: [ home, network-bind, network, can-bus, serial-port, i2c, spi]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas

  client:
    command: bin/fixgwc
    plugs: [network]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH


